### ISSUE TITLE
Same UUID Error

### ISSUE THREAD

**Issue by faruk604** [jonavila/homebridge-crestron#7]
When I try to start homebridge, I take this error. What I need to do ?

 homebridge :
--version 0.4.50

Config.json : 

`{
  "bridge": {
    "name": "Homebridge",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "031-45-154"
  },

  "platforms": [
    {
      "platform": "Crestron",
      "name": "RMC3",
      "host": "192.168.1.200",
      "port": "9050",
      "devices": [
        {
          "id": 1,
          "type": "LightSwitch",
          "name": "Lights 1",
          "manufacturer": "Crestron",
          "model": "CLW-SWEX-P"
        },
        {
          "id": 2,
          "type": "LightSwitch",
          "name": "Lights 2",
          "manufacturer": "Crestron",
          "model": "CLW-SWEX-P"
        },
        {
          "id": 1,
          "type": "LightDimmer",
          "name": "Dimmer 1",
          "manufacturer": "Crestron",
          "model": "CLW-DIMEX-P"
        },
		{
          "id": 2,
          "type": "LightDimmer",
          "name": "Dimmer 2",
          "manufacturer": "Crestron",
          "model": "CLW-DIMEX-P"
        },
        {
          "id": 1,
          "type": "GenericSwitch",
          "name": "Switch 1",
          "manufacturer": "DIRECTV",
          "model": "HR-54"
        },
        {
          "id": 2,
          "type": "GenericSwitch",
          "name": "Switch 2",
          "manufacturer": "DIRECTV",
          "model": "HR-54"
        }
      ]
    }
  ]
}`

 Error : 

`C:\Users\*****>homebridge

[2019-10-9 6:13:38] Loaded config.json with 0 accessories and 1 platforms.
[2019-10-9 6:13:38] ---
[2019-10-9 6:13:38] Loaded plugin: homebridge-crestron-simpl
[2019-10-9 6:13:38] Registering platform 'homebridge-crestron-simpl.Crestron'
[2019-10-9 6:13:38] ---
[2019-10-9 6:13:38] Loading 1 platforms...
[2019-10-9 6:13:38] [RMC3] Initializing Crestron platform...
[2019-10-9 6:13:38] Error: Cannot add a Characteristic with the same UUID as another Characteristic in this Service: 00000023-0000-1000-8000-0026BB765291
    at Service.AccessoryInformation.Service.addCharacteristic (C:\Users\*****\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\lib\Service.js:80:13)
    at new Service.AccessoryInformation (C:\Users\*****\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\lib\gen\HomeKitTypes.js:2660:8)
    at new BaseDevice (C:\Users\*****\node_modules\homebridge-crestron-simpl\dist\index.js:2935:25)
    at new LightSwitch (C:\Users\*****\node_modules\homebridge-crestron-simpl\dist\index.js:3279:5)
    at C:\Users\*****\node_modules\homebridge-crestron-simpl\dist\index.js:3391:30
    at Array.forEach (<anonymous>)
    at C:\Users\*****\node_modules\homebridge-crestron-simpl\dist\index.js:3388:15
    at C:\Users\*****\node_modules\homebridge-crestron-simpl\dist\index.js:347:11
    at baseForOwn (C:\Users\*****\node_modules\homebridge-crestron-simpl\dist\index.js:883:20)
    at C:\Users\*****\node_modules\homebridge-crestron-simpl\dist\index.js:900:14`

**Comment by jonavila** [comment]
@faruk604 Sorry for the super late reply. The next branch currently has a fix for this. It requires the latest beta version of homebridge 0.4.54-beta.42 and the beta version of this package is published in NPM at `@jonavila/homebridge-crestron`
